### ISSUE TITLE
Testing application

### ISSUE THREAD

**Issue by pshahsancsoft** [sancsoft/hq#145]
**Clients**
_Filtering_

- [ ] Search filtering

Saves my search filter, but not my other filters once I leave the page. If we save filters once user leaves page and returns, how do they stop filtering? For example, once I start filtering billing email, I can't escape filtering it asc or desc. 
Filtering makes capital letters have lesser value, should we be doing this?

- [ ]  Filter client name
- [ ] Rate
Once I edit a client, I should be able to click back to client list 

- [ ] Filter billing email
when I filter, it shows clients with no email ("None") above clients with actual emails 

- [ ] Create Client
- [ ] Edit
- [ ] view client
       Does the month to date, last month to date, year to date, all time to date, need reformatting?
       View buttons don't do anything
- [ ] View client quotes
       Add quote button doesn't do anything

- [ ] View Client Services
       Is add service button supposed to go to projects/create?

- [ ] 

- [ ] View Client invoices
       Add invoices button doesn't do anything

- [ ] Edit client details 

**Projects**

- [ ] Search filter
- [ ] Project Manager filter
- [ ] Project Status filter
       Does not work
- [ ] Search filter
- [ ] Project full name filter 
- [ ] Client name filter
- [ ] PM Filter
- [ ] Status
- [ ] Complete %

- [ ] Create project
- [ ] View project
       They all say 00000.00 or total billed
       All psrs are empty

**Quotes**

Is there supposed to be a quote number, charge code, or created at filter?
- [ ] Search filter
- [ ] Quote number filter
        There is no filter here, not sure if there is supposed to be one

- [ ] Client name filter
- [ ] Status
       they all have 
- [ ] Create Quote
      Pressing SAVE creates it, but shows no indication of completion to user
      Pressing save doesn't redirect 

- [ ]  Quote list redirect anchor 

**Services**
    Not populated
    Is create service supposed to go to projects?

**Invoices**
Not populated 
Create invoice button does 

**PSR**
- [ ] Search filter
- [ ] Project manager
- [ ]Submitted
- [ ] Date filters 
       If you put in a date, then press clear, the network request fails

- [ ] PSR View
      Select staff member not populated
     table not populated 

**Users**
- [ ] Search filter
- [ ] There is no other filtering 
- [ ] Create user 
     says unexpected error occurred, unless I say yes to all inputs
- [ ] Edit User 
- [ ]  User list anchor 

**Staff**

- [ ] Search filter
- [ ] name filter
- [ ] first name filter
- [ ] last name filter
- [ ] working hours filter
- [ ] vacation hours
- [ ] start date
- [ ] end date filter
- [ ] create staff
- [ ] edit staff
- [ ] staff list anchor

**Charge Codes**
- [ ] Search filter
- [ ] Charge code filter
- [ ] Billable filter
- [ ] Project Name filter
- [ ] Quote Name filter 
- [ ] Create charge code
- [ ] Edit Chargecode
       should I be able to edit the quote name, service agreement name because edit chargecode does not let me
Should I be able to view the charge code description in the table?

**Time**

- [ ] Search filter
- [ ] Select staff
- [ ] Select client
- [ ] select project
- [ ] time accepted
- [ ] invoiced
- [ ] period
    clearing custom dates, returns error from network request
- [ ] export 
- [ ] edit

**Comment by rmaffitsancsoft** [comment]
# Clients
- [ ] Sorting needs to be persisted in the service so if a user clicks into a client and goes back, the table should have same data in it. Currently the sort column and direction are not being persisted.
- [ ] Add `Client List` link to client details page
- [ ] Client project list - Project status filter is busted, mismatched enum?
- [ ] Create Quote - Link to create quote page
- [ ] Create service - Disable button
- [ ] Create invoice - Disable button
- [ ] Project list - View should go to project detail page

# Projects
- [ ] Project list - Project status filter busted, mismatched enum?
- [ ] Project view - PSR list blue background should match active PSR
- [ ] Project view - PSR time list is inaccurate
- [ ] Project edit - not populating project info

# Quotes
- [ ] Quote create - Redirect back to list after successful save to API, show toast
- [ ] Quote create - update list link to use routerLink

# Services
- [ ] Service list - Disable create button

# Invoices
- [ ] Invoice list - Disable create button

# PSR
- [ ] PSR date filter - if empty string pass null to API

# Users
- [ ] User create - Show validation results (APIError) on bad response from server, also apply to edit form

# Time
- [ ] Time list - if empty string pass null to API
