### ISSUE TITLE
Long string in description causes error

### ISSUE THREAD

**Issue by bmelkeysancsoft** [sancsoft/hq#238]
Saving an entry with the following string in the description causes an error:
"Changes such that configuration process occurs upon receipt of relevant Drive Status CAN messages or one second whichever is the soonest and the startup logo is displayed until configuration is complete."

**Comment by rmaffitsancsoft** [comment]
Talked with Ben, he was able to re-submit. Seems to be related to login error as he was able to enter it after refreshing and logging in.
