### ISSUE TITLE
PSR - LIst - Filter updates

### ISSUE THREAD

**Issue by rmaffitsancsoft** [sancsoft/hq#99]
- [x] Save current filters/items per page/current page in session so when you navigate back to the list you don't lose where you were at
- [x] Add a date filter (Filter to intersection of PSR start/end dates)
- [x] Rename "Is Submitted?" in dropdown to "All"

Questions
- Should we add labels to the filters for clarity? We could potentially reuse the label from the edit forms. Checking in with design team.

**Comment by amahdysancsoft** [comment]
> Questions
> 
> * Should we add labels to the filters for clarity? We could potentially reuse the label from the edit forms. Checking in with design team.
**Yes, totally agree, since we are developing this system so we know what this does but for a user who was not introduced to the system, it will be confusing.**
